Section header fix
razeware/emitron-iOS pull request #479
Opened 2020-09-14 18:54 UTC by VegetarianZombie

This pull request resolves the issue with additional lines rendering in iOS 14. This was due to list sections being nested inside of each other. This pull request refactors the sections inside of a group that resolves the issue. It also sets the width of the list cell to the width of the device.
 
Before:

![Screen Shot 2020-09-14 at 2 53 04 PM](https://user-images.githubusercontent.com/973751/93126180-0ce5ba80-f69a-11ea-9f1c-4e9b8fc75609.png)

After:

![Screen Shot 2020-09-14 at 2 41 32 PM](https://user-images.githubusercontent.com/973751/93125756-934dcc80-f699-11ea-82a9-0fc85572e0ae.png)

Note: The project contains a Group struct that causes a name collision with the SwiftUI Group.

2020-09-15 08:41 UTC, sammyd reviewed
This looks good to me. Since it requires Xcode 12, I want to wait until we can switch CI to merge it. Hopefully it'll be in the next day or so.

2020-09-15 09:28 UTC, sammyd commented
@VegetarianZombie actually, how come the styling of the header has changed? I don't think it should be centred / capitalised.

2020-09-15 14:02 UTC, VegetarianZombie commented
Hi Sam - Okay, that was a mistake on my part. I'll update the PR to use the correct styling information.

2020-09-20 14:35 UTC, sammyd requested changes
As specified above—not sure why the typography has changed...

2020-09-20 14:35 UTC, sammyd commented on Emitron/Emitron/UI/Shared/Content Detail/CourseHeaderView.swift
>        Text(name)
Not sure why, but this is now centred and capitals?

2020-09-20 16:06 UTC, VegetarianZombie commented
Hi @sammydl, I investigated the issue today. The casing change is a result from iOS 14. By default, section headers appear now to be uppercased. This can be changed with the 'textCase' modifier.

I updated the pull request to left justify the header. I also added a conditional statement to set the text case on iOS 14 and above. Pre iOS 14 is fine.

2020-09-20 20:40 UTC, sammyd commented
Thanks @VegetarianZombie. I'll get this rebased, resolve the merge conflicts, and get it merged.

2020-09-20 21:12 UTC, sammyd approved these changes
:+1: I've rebased it, and will go ahead and merge it once CI has completed.

Nice work—thanks for this @VegetarianZombie

2020-09-20 21:22 UTC, sammyd commented
This fixed #465

2020-09-20 21:22 UTC, merged